### ISSUE TITLE
cannot find symbol   symbol:   variable FlayMenu

### ISSUE THREAD

**Issue by mrizkir** [mas-elkhanza/SIMRS-Khanza#133]
Selamat pagi,

saya coba menjalakan chanza pertama kali di Netbeans kemudian mendapatkan error sebagai berikut :

**Variabel FlayMenu tidak dikenali**

```
run:
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Uncompilable code - cannot find symbol
  symbol:   variable FlayMenu
  location: class simrskhanza.frmUtama
	at simrskhanza.frmUtama.<init>(frmUtama.java:1010)
	at simrskhanza.frmUtama.getInstance(frmUtama.java:1109)
	at simrskhanza.SIMRSKhanza.lambda$main$0(SIMRSKhanza.java:21)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
BUILD SUCCESSFUL (total time: 10 seconds)
```

Object FlayMenu ini di frmUtama dideklarasikan di Bagian mana ya pak ?

**Comment by simkeskhanza** [comment]
Terdapat kekurangan file png di folder 48x48, silahkan lakukan pull ulang.
.
.
mohon issue ini untuk diclosed. thx
