### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jxl/write/WriteException

### ISSUE THREAD

**Issue by enzothea** [mas-elkhanza/SIMRS-Khanza#134]
assalamualikum
saya install pada win11 64bit kemudian muncul error seperti ini. mohon solusinya. Terimakasih

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jxl/write/WriteException
        at simrskhanza.frmUtama.<init>(frmUtama.java:1012)
        at simrskhanza.frmUtama.getInstance(frmUtama.java:1124)
        at simrskhanza.SIMRSKhanza.lambda$main$0(SIMRSKhanza.java:21)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: jxl.write.WriteException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more

**Comment by simkeskhanza** [comment]
Mohon dipastikan kembali pada netbeans saudara, terdapat plugin jfx belum terinstall sepenuhnya. thx
.
.
Mohon issue ini untuk diclosed. thx
